global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/{}/{}/{}'

route:
  repeat_interval: 1h
  receiver: 'gmail-notifications'
  routes:
  # - receiver: alertsnitch
  #   continue: true
  - receiver: 'gmail-notifications'
    continue: true
  - receiver: 'slack-notifications'
    group_by: [alertname, datacenter, app]
receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: example@gmail.com
    from: example@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: example@gmail.com
    auth_identity: example@gmail.com
    auth_password: password
    send_resolved: true
# - name: alertsnitch
#   webhook_configs:
#   - url: http://alertsnitch:9567/webhook
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
