global:
  scrape_interval: 15s

# Rules and alerts are read from the specified file(s)
rule_files:
  - 'alerts/*.yml'

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    # dns_sd_configs:
    #   - names:
    #       - "tasks.cadvisor"
    #     type: "A"
    #     port: 8080
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]
    # dns_sd_configs:
    #   - names:
    #     - "tasks.node_exporter"
    #     type: "A"
    #     port: 9100
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [ http_2xx ]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - /etc/prometheus/file_sd/*.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        replacement: https://$1/  # Make probe URL be like https://1.2.3.4:443/
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
      - source_labels: [__meta_dns_name]
        target_label: __param_hostname  # Make domain name become 'Host' header for probe requests
      - source_labels: [__meta_dns_name]
        target_label: vhost  # and store it in 'vhost' label
  - job_name: "mysql"
    static_configs:
      - targets: ["mysqld_exporter:9104"]
    # dns_sd_configs:
    #   - names:
    #       - "mysql_exporter"
    #     type: "A"
    #     port: 9104
